feat: Socialmedia sharing
blockchain-lab-um/masca pull request #557
Opened 2024-01-29 10:19 UTC by andyv09

2024-01-29 10:40 UTC, Vid201 commented on packages/dapp/src/messages/en.json
> +    "share-link-description": "Share your credential on social media:",
Remove "on social media"

2024-01-29 10:43 UTC, pseudobun commented
Fix prettier warnings.
```
[warn] src/app/[locale]/app/(public)/share-presentation/[id]/credentialPanel.tsx
[warn] src/app/[locale]/app/(public)/share-presentation/[id]/formatedView.tsx
[warn] src/app/[locale]/app/(public)/share-presentation/[id]/page.tsx
[warn] src/components/ShareCredentialModal/index.tsx
[warn] Code style issues found in 4 files. Run Prettier to fix.
```

2024-01-31 08:53 UTC, pseudobun requested changes

2024-01-31 08:53 UTC, pseudobun commented on packages/dapp/src/app/[locale]/app/(public)/share-presentation/[id]/page.tsx
> +  const url = 'http://localhost:3000';
Prepare this for deployment.

2024-01-31 08:53 UTC, pseudobun commented on packages/dapp/src/app/api/og/route.tsx
> +      // If 1 VC show VC
Remove this comment.

2024-01-31 08:53 UTC, pseudobun commented on packages/dapp/src/app/api/og/route.tsx
> +      // If more...
This one too.

2024-02-07 07:46 UTC, pseudobun commented
Resolve prettier issues:
```
./src/app/[locale]/app/(public)/share-presentation/[id]/page.tsx
1:10  Error: 'ResolvingMetadata' is defined but never used.  unused-imports/no-unused-imports
```

2024-02-08 15:26 UTC, pseudobun requested changes

2024-02-08 15:26 UTC, pseudobun commented on packages/dapp/src/app/api/og/route.tsx
> +                    di
Is this supposed to be here?

2024-02-12 13:22 UTC, merged